apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-np-service
spec:
  selector:
    app: phpmyadmin
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31001

