apiVersion: apps/v1
kind: Deployment
metadata:
  name: db1-deployment
  labels:
    app: db1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db1
  template:
    metadata:
      labels:
        app: db1
    spec:
      containers:
        - name: db1
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: mysqldb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db1-secrets
                  key: ROOT_PASSWORD
            - name: MYSQL_USER
              value: site1_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db1-secrets
                  key: SITE1_USER_PASSWORD
            - name: MYSQL_DATABASE
              value: site1
      volumes:
        - name: mysqldb
          persistentVolumeClaim:
            claimName: db1-disk