apiVersion: apps/v1
kind: Deployment
metadata:
  name: site1-deployment
  labels:
    app: site1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site1
  template:
    metadata:
      labels:
        app: site1
    spec:
      containers:
        - name: app1
          image: wordpress:5.2
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: db1-service
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db1-secrets
                  key: SITE1_USER_PASSWORD