apiVersion: v1
kind: Service
metadata:
  name: site1-service
spec:
  type: NodePort
  selector:
    app: site1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30120